language: java
sudo: false
cache:
  directories:
    - '$HOME/.m2/repository'


install: true

script: "
wget https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip;
unzip -qq apache-maven-3.6.3-bin.zip;
export M2_HOME=$PWD/apache-maven-3.6.3;
export PATH=$M2_HOME/bin:$PATH;

if [ ${TRAVIS_PULL_REQUEST} = 'false' ];
then
    mvn -v;
    mvn clean deploy --no-transfer-progress --batch-mode --settings etc/settings.xml -Dfmt.skip=true;
else
    mvn -v;
    mvn clean verify --no-transfer-progress --batch-mode --settings etc/settings.xml -Dmaven.javadoc.skip=true -Dfmt.skip=true;
fi"

dist: trusty

jdk:
  - openjdk11

# whitelist
branches:
  only:
    - develop

env:
  global:
    - secure: "pDTp3TujySuBn3IV5QzgYSsLdLHRDApm2dvKT5P8aHgLDF2tM59a5fWYuA+MiTrZdpbxsUXzxrl4l5+cQyLGI10/hu4R7uft4k46Da78xNA5REki+YU7rjCA6RXdWUuXyhLNFYPWVNt3mgi7YfsyNwRrtS3FQQZn1BOfDJ0s5Vo="
    - secure: "YwWFnNl4cBEKzRiMjKlfp1VieMkWp4LGENMKzlVs7hy3TWFz4A2pJpRUX76qqWV/6h6vOqY6cogql3NCietzJbspSgwl7MkboPVXYn9HgQkPwrcdQh/h9PzsC63iOW4jyIqHzjVT36MYLYrXTvRrqdMHUjFJmObiNt1KY674d7g="

# matrix:
#  - LC_ALL=C
#  - LC_ALL=pl_PL
#  - LC_ALL_zh_CN
